### ISSUE TITLE
Launch Method not saving

### ISSUE THREAD

**Issue by brandonicon** [jenkinsci/azure-container-agents-plugin#103]
### Jenkins and plugins versions report

Jenkins: 2.319.3
OS: Linux - 5.11.0-1028-azure
---
Office-365-Connector:4.15.2
ace-editor:1.1
active-directory:2.25.1
antisamy-markup-formatter:2.7
apache-httpcomponents-client-4-api:4.5.13-1.0
atlassian-jira-software-cloud:1.4.5
authentication-tokens:1.4
authorize-project:1.4.0
azure-ad:191.vfc8019068670
azure-cli:0.9
azure-container-agents:222.va22f04771da0
azure-credentials:198.vf9c2fdfde55c
azure-sdk:85.v4817a_b_8a_7124
blueocean-commons:1.25.2
blueocean-rest:1.25.2
bootstrap4-api:4.6.0-3
bootstrap5-api:5.1.3-4
bouncycastle-api:2.25
branch-api:2.7.0
build-timeout:1.20
caffeine-api:2.9.2-29.v717aac953ff3
checks-api:1.7.2
cloud-stats:0.27
cloudbees-folder:6.17
command-launcher:1.6
configuration-as-code:1346.ve8cfa_3473c94
copyartifact:1.46.2
credentials:1074.v60e6c29b_b_44b_
credentials-binding:1.27.1
dashboard-view:2.18
display-url-api:2.3.5
docker-commons:1.19
durable-task:493.v195aefbb0ff2
echarts-api:5.2.2-2
email-ext:2.87
extended-read-permission:3.2
font-awesome-api:5.15.4-5
git:4.10.3
git-client:3.11.0
git-server:1.10
github:1.34.1
github-api:1.301-378.v9807bd746da5
github-branch-source:2.11.4
handlebars:3.0.8
jackson2-api:2.13.1-246.va8a9f3eaf46a
javax-activation-api:1.2.0-2
javax-mail-api:1.6.2-5
jaxb:2.3.0.1
jdk-tool:1.5
jjwt-api:0.11.2-9.c8b45b8bb173
jnr-posix-api:3.1.7-1
jquery3-api:3.6.0-2
jsch:0.1.55.2
junit:1.54
kubernetes-cli:1.10.3
kubernetes-client-api:5.11.2-182.v0f1cf4c5904e
kubernetes-credentials:0.9.0
ldap:2.7
lockable-resources:2.14
mailer:408.vd726a_1130320
matrix-auth:3.0.1
matrix-project:1.20
momentjs:1.1.1
okhttp-api:4.9.3-105.vb96869f8ac3a
pam-auth:1.7
pipeline-build-step:2.15
pipeline-github-lib:36.v4c01db_ca_ed16
pipeline-graph-analysis:188.v3a01e7973f2c
pipeline-input-step:446.vf27b_0b_83500e
pipeline-milestone-step:100.v60a_03cd446e1
pipeline-model-api:1.9.3
pipeline-model-definition:1.9.3
pipeline-model-extensions:1.9.3
pipeline-rest-api:2.21
pipeline-stage-step:291.vf0a8a7aeeb50
pipeline-stage-tags-metadata:1.9.3
pipeline-stage-view:2.21
plain-credentials:1.8
plugin-util-api:2.13.0
popper-api:1.16.1-2
popper2-api:2.11.2-1
resource-disposer:0.17
role-strategy:3.2.0
scm-api:595.vd5a_df5eb_0e39
script-security:1131.v8b_b_5eda_c328e
snakeyaml-api:1.29.1
ssh-credentials:1.19
ssh-slaves:1.33.0
sshd:3.1.0
structs:308.v852b473a2b8c
timestamper:1.17
token-macro:270.v8c2ce50dc4fc
trilead-api:1.0.13
windows-azure-storage:371.v19a0f02c7603
workflow-aggregator:2.6
workflow-api:1136.v7f5f1759dc16
workflow-basic-steps:2.24
workflow-cps:2648.va9433432b33c
workflow-cps-global-lib:552.vd9cc05b8a2e1
workflow-durable-task-step:1121.va_65b_d2701486
workflow-job:1145.v7f2433caa07f
workflow-multibranch:706.vd43c65dec013
workflow-scm-step:2.13
workflow-step-api:622.vb_8e7c15b_c95a_
workflow-support:813.vb_d7c3d2984a_0
ws-cleanup:0.40

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 20.04.3 LTS (GNU/Linux 5.11.0-1028-azure x86_64)

### Reproduction steps

1. Manage Jenkins
2. Manage Nodes & Clouds
3. Configure Clouds
4. Change Launch Method from **Inbound agent** to **SSH**

### Expected Results

Launch method is changed to SSH from inbound agent

### Actual Results

Launch method remains as inbound agent

**Comment by timja** [comment]
Are you sure it's not saving? There's a UI bug where it displays the wrong one here: https://github.com/jenkinsci/azure-container-agents-plugin/issues/79

**Comment by brandonicon** [comment]
> Are you sure it's not saving? There's a UI bug where it displays the wrong one here: #79
> 
> You can checked the saved config on disk in `config.xml`

Confirmed that its the mentioned issue.
