### ISSUE TITLE
[Maintenance] Update Azure SDK and remove Workaround

### ISSUE THREAD

**Issue by sparsick** [jenkinsci/azure-container-agents-plugin#105]
If a new version of Azure SDK with the fix for Azure issue https://github.com/Azure/azure-sdk-for-java/issues/27083 is released, then the workaround for #101 can be removed.

**Comment by sparsick** [comment]
Azure SDK Resource manager 2.13.0 contains the fix

**Comment by timja** [comment]
Seems to be tagged but not released.

**Comment by sparsick** [comment]
Some artefacts are already on maven central like `azure-resourcemanager-containerinstance`, but not the wrapper artefact `azure-resourcemanager`, that is needed by azure-sdk-plugin.

**Comment by sparsick** [comment]
It seems that now is everything in Maven Central. I open a PR in azure-sdk-plugin.

**Comment by timja** [comment]
azure sdk released in https://github.com/jenkinsci/azure-sdk-plugin/releases/tag/106.v552de1e64d56
