### ISSUE TITLE
Must be unique error when trying to define a pod template that mounts an azure file share.

### ISSUE THREAD

**Issue by chrisrpatterson** [jenkinsci/azure-container-agents-plugin#13]
Error in provisioning; slave=com.microsoft.jenkins.containeragents.KubernetesAgent[jenkins-agent-njx6q], template=com.microsoft.jenkins.containeragents.PodTemplate@1bf88ccc: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://cp-aks-cp-aks-5e8113-cd6613fc.hcp.eastus.azmk8s.io/api/v1/namespaces/default/pods. Message: Pod "jenkins-agent-njx6q" is invalid: spec.containers[0].volumeMounts[1].mountPath: Invalid value: "/mnt/jenkins": must be unique. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.containers[0].volumeMounts[1].mountPath, message=Invalid value: "/mnt/jenkins": must be unique, reason=FieldValueInvalid, additionalProperties={})], group=null, kind=Pod, name=jenkins-agent-njx6q, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=Pod "jenkins-agent-njx6q" is invalid: spec.containers[0].volumeMounts[1].mountPath: Invalid value: "/mnt/jenkins": must be unique, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).

**Comment by zackliu** [comment]
Could you give more configuration details. Did your `Working Dir` duplicated with your `Azure File Mount Path`?

**Comment by chrisrpatterson** [comment]
Yes they are the same and it seems those should be independent.  I want to mount the file share as the working directory so I can persist sources and build outputs between builds.

**Comment by zackliu** [comment]
In fact we mount a `Empty Volume` to the `Working Dir` to prevent the permission issue.
I will add a checkbox to let user decide whether to mount `Empty Volume` automatically in the next release.
I don't recommend to mount Azure file to your `working dir` directly because Azure file is really slow in reading and writing small files. Instead, you can copy what you need to Azure file after build.

**Comment by chrisrpatterson** [comment]
ok that makes sense.  Thank you.

**Comment by zackliu** [comment]
I decide not to mount `Empty Volume` automatically. So you can mount what you need to working directory in the next version

**Comment by zackliu** [comment]
The feature released in 0.4.0
