### ISSUE TITLE
Provide more information on "jenkins-slave" script

### ISSUE THREAD

**Issue by atrauzzi** [jenkinsci/azure-container-agents-plugin#17]
Would love to know what the intent is with this script so that I can correctly match the lifecycle.

**Comment by zackliu** [comment]
What `jenkins-slave` script? Do you means image?

**Comment by chenkennt** [comment]
@atrauzzi jenkins-slave is owned by jenkins, if you need more information about it, please refer to the official docker hub: https://hub.docker.com/r/jenkinsci/jnlp-slave/ or post an issue in their repository.
