### ISSUE TITLE
Insufficient document, no validation steps mentioned

### ISSUE THREAD

**Issue by Rupeshravi93** [jenkinsci/azure-container-agents-plugin#213]
### Describe your use-case which is not covered by existing documentation.

followed the steps mentioned in https://plugins.jenkins.io/azure-container-agents/

The steps are getting over at "Configure the Container Template", There is no step to create and connect to the container node or to validate the steps.

Please guide me to the correct document for the setup, I am using my Jenkins in my local system and the expectation is to connect to azure container instance from Jenkins using the agent

**Comment by sparsick** [comment]
It seems that you misunderstand the plugin. You configure a container template that would be used to create a container on the fly. No need to connect to an already running container

**Comment by Rupeshravi93** [comment]
@sparsick Thanks for the clarification. While creating the pipeline, in the build section I am not getting "Azure Container services" in the drop down. Can you please help me which option to select in build step so that the pipeline runs on this plugin.

**Comment by sparsick** [comment]
@Rupeshravi93 when you add a container template, you have to set a label for that container. In your pipeline script, you can use this label name as your agent. Then the container will be created automatically.

**Comment by Rupeshravi93** [comment]
Thanks @sparsick
