### ISSUE TITLE
Azure contains Agents - Private IP Address

### ISSUE THREAD

**Issue by cheetisrinivas** [jenkinsci/azure-container-agents-plugin#25]
We are using Azure Container Agents Plugin to deploy Jenkins Agents.

I am following instructions here: https://wiki.jenkins.io/display/JENKINS/Azure+Container+Agents+Plugin ,with Jenkins Master  in-house.

We allowed Jenkins Master Host IP on the VPN tunnel from our network to Azure.

Azure Container Agents are being initiated when I run the build from Jenkins, however they are unable to communicate back to Jenkins master via  our gateway since they are getting public IP's.

How do I make sure Jenkins agents are getting a IP from our address space and communicate back to our Jenkins Master.

**Comment by zackliu** [comment]
Are you using JNLP slave or SSH slave?
I think SSH slave is more suitable for your scenario because agent don't need to communicate back to master.
It's a known issue that jnlp slave usually failed to connect to master and it's difficult to do troubleshooting.

**Comment by cheetisrinivas** [comment]
Either JNLP or SSH slave are unable to get a private IP in our address space or VLAN is Azure. They are getting a public IP in Azure, hence they are unable to communicate with master.

**Comment by jleonelion** [comment]
@zackliu it looks like ACI supports allocating containers to a virtual network (and no public IP) if those containers are associated with a [networkProfile](https://docs.microsoft.com/en-us/azure/templates/microsoft.network/2019-04-01/networkprofiles).  Is this a capability you are working on?  If not, would you be ok if I attempted to implement this capability enhancement?

**Comment by apurbain** [comment]
Can you please add this capability. We are unable to use this agent due to public IP assignment.
