### ISSUE TITLE
unable to deploy windows container in aci

### ISSUE THREAD

**Issue by EZhao-Quest** [jenkinsci/azure-container-agents-plugin#31]
I want to run a windows container in aci , but always get Error code
ResourceDeploymentFailure
Message
The resource operation completed with terminal provisioning state 'Canceled'. 
![aciconfig](https://user-images.githubusercontent.com/12058239/46651409-7cabba80-cbd2-11e8-97c4-f9b21afc9c68.PNG)

I can see container creating in azure portal, but after few minutes , I can see the above error message. then container deleted.

**Comment by EZhao-Quest** [comment]
here are the the image and docker file :https://github.com/JonCubed/docker-jenkins-jnlp-slave-windows

**Comment by timja** [comment]
It works on ci.jenkins.io, I assume there was an issue in the windows docker agent which has been fixed now
