### ISSUE TITLE
Connect to null failed: null

### ISSUE THREAD

**Issue by mordf** [jenkinsci/azure-container-agents-plugin#34]
When i'm clicking on **TEST CONNECTION** button i'm getting: `Connect to null failed: null`

The credentials are fine since it recognizes my AKS clusters when i'm putting them.

**Comment by aysahu** [comment]
Hi,

I am also facing similar issue with plugin version 0.4.1, Jenkins version 1.150, error logs below.

`Feb 04, 2019 11:02:54 PM WARNING com.microsoft.jenkins.containeragents.KubernetesCloud$ProvisionCallback call
Error in provisioning; slave=com.microsoft.jenkins.containeragents.KubernetesAgent[checkout-qtz3r], template=com.microsoft.jenkins.containeragents.PodTemplate@1455fb53: java.lang.NullPointerException`

`Feb 04, 2019 11:02:54 PM WARNING com.microsoft.jenkins.containeragents.KubernetesCloud deletePod
Failed to terminate pod for slave checkout-qtz3r
java.lang.NullPointerException
	at com.microsoft.jenkins.containeragents.KubernetesService.getKubernetesClient(KubernetesService.java:223)
	at com.microsoft.jenkins.containeragents.KubernetesCloud.connect(KubernetesCloud.java:101)
	at com.microsoft.jenkins.containeragents.KubernetesCloud.deletePod(KubernetesCloud.java:285)
	at com.microsoft.jenkins.containeragents.KubernetesAgent$1.run(KubernetesAgent.java:100)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by ToruMakabe** [comment]
Same here. @mordf @aysahu What version of AKS do you use? I use 1.12.4.

**Comment by aysahu** [comment]
@ToruMakabe  I am using 1.11.5 with VNET enabled.

**Comment by mordf** [comment]
I’m also using 1.11.5

**Comment by mordf** [comment]
I’m also using 1.11.5

**Comment by kristianhald** [comment]
We used AKS version 1.11.2, then upgraded to 1.11.6 to try an fix the issue.
Also tried creating a Jenkins server using the Microsoft template from Azure Marketplace with an AKS 1.12.4. Same error.

When I press the 'Test Connection' button, I can see that I get an error in the Activity Log for the resource group:
![image](https://user-images.githubusercontent.com/10573517/52271970-7ee61180-2945-11e9-9a81-ab222c1f94f2.png)

**Comment by ToruMakabe** [comment]
@kristianhald I got the same message "Could not find role name clusterAdmin". So I tested all versions of API by calling them directly. Then, 2018-08-01-preview only failed with the same error.

**Comment by aysahu** [comment]
Hey,

Anyone is working on our issue or it is just no body is listening us ?

**Comment by ToruMakabe** [comment]
@aysahu It seems the cause is that this plugin dynamically get the latest version API of AKS. The latest API published last week and it does not support get accessProfile. Azure team is making a hotfix to mitigate this issue. 
https://github.com/jenkinsci/azure-acs-plugin/issues/16#issuecomment-461228540

**Comment by aysahu** [comment]
@ToruMakabe  Thanks for information.

**Comment by mordf** [comment]
@ToruMakabe Thanks a lot for the update

**Comment by kristianhald** [comment]
Our Jenkins is working again with AKS.

Azure has deployed a hotfix for the latest API change.
https://github.com/Azure/AKS/releases/tag/2019-02-07

As I understand the change, they have made an endpoint, deprecated instead of removing it completely. The endpoint will be removed at a later date, so the plugin will probably need an update for this.

**Comment by mordf** [comment]
Working for me as well, closing the issue.
