### ISSUE TITLE
Connect to null failed: null reopen

### ISSUE THREAD

**Issue by Yusuke-Hiramatsu** [jenkinsci/azure-container-agents-plugin#36]
AKS Pod Template has exception logs recorded on April 6, messaging that NullPointerException
in Jenkins master, resulted in any pod unavailable as a ssh slave. It seems that the event is similar
cause of the ticket, "Connect to null failed: null #34", suggested that the past problem could have 
been re-invoked again. 

In detail log/messages are shown bellow;
`Error in provisioning; slave=com.microsoft.jenkins.containeragents.KubernetesAgent[ssh-slave-rj4zb], template=com.microsoft.jenkins.containeragents.PodTemplate@31b0e567: java.lang.NullPointerException Apr 06, 2019 1:31:21 AM INFO com.microsoft.jenkins.containeragents.KubernetesCloud$ProvisionCallback call Removing Jenkins node: ssh-slave-rj4zb Apr 06, 2019 1:31:21 AM INFO com.microsoft.jenkins.containeragents.KubernetesCloud deletePod Terminating container instance for slave ssh-slave-rj4zb Apr 06, 2019 1:31:21 AM INFO okhttp3.internal.platform.Platform log ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
Apr 06, 2019 1:31:21 AM INFO okhttp3.internal.platform.Platform log ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
Apr 06, 2019 1:31:22 AM WARNING com.microsoft.jenkins.containeragents.KubernetesCloud deletePod Failed to terminate pod for slave ssh-slave-rj4zb java.lang.NullPointerException
	at com.microsoft.jenkins.containeragents.KubernetesService.getKubernetesClient(KubernetesService.java:223)
	at com.microsoft.jenkins.containeragents.KubernetesCloud.connect(KubernetesCloud.java:101)
	at com.microsoft.jenkins.containeragents.KubernetesCloud.deletePod(KubernetesCloud.java:285)
	at com.microsoft.jenkins.containeragents.KubernetesAgent$1.run(KubernetesAgent.java:100)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`
To confirm, Jenkins AKS pod template configuration tested connection to AKS Cluster by 
"Test Connection" button on Jenkins Web UI. "Connect to null failed: null" showed as an error 
message. Service Principal as credential has correctly authenticated.

In addition, AKS version both with 1.12.4 and 1.12.6 lead to the same problem.
And azure-container-agents-plugin has recently no source code with any commit, 
possibly not involved in a cause of the trouble.
[https://github.com/jenkinsci/azure-container-agents-plugin](url)

In terms of kubelet, as following in normal;
$ kubectl config get-contexts
$ kubectl config use-context <AKS Cluster name>

Above all, please help information useful to resolve the trouble.

**Comment by mordf** [comment]
I think it's the same issue I opened yesterday:
https://github.com/jenkinsci/azure-container-agents-plugin/issues/35
And it's related to the issue that happened in the passed:
https://github.com/jenkinsci/azure-container-agents-plugin/issues/34


The last time it happened, Toru Makabe (https://github.com/ToruMakabe ) helped out

**Comment by Yusuke-Hiramatsu** [comment]
This issue is duplicated with https://github.com/jenkinsci/azure-container-agents-plugin/issues/35.
