### ISSUE TITLE
Cannot pull container from my Azure Container Registry

### ISSUE THREAD

**Issue by jleonelion** [jenkinsci/azure-container-agents-plugin#40]
I'm struggling to create an ACI Container Template that pulls Docker Image from my Azure Container Registry and hoping someone can help. 

As background, I have the following setup:

1.  Setup a Jenkins server with a project that executes on a container node (jenkinsci/ssh-slave) based on these instructions: [Using Azure container instances as Jenkins build agents](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-jenkins)
1. Cloned the jenkinsci/ssh-slave from https://github.com/jenkinsci/docker-ssh-slave.git and rebuilt with the tag docker-ssh-slave-example
1. Created an Azure Container Registry and pushed a copy of the docker-ssh-slave-example container to that registry based on [Deploy an Azure container registry and push a container image](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-tutorial-prepare-acr)
1. In Jenkins config, I added an Aci Container Template with a Docker Image of "&lt;my registry&gt;.azurecr.io/docker-ssh-slave-example"

I'm stuck on how to create the "Private Registry Credential".  It's not clear to me what "Kind" of credential I need to create so Jenkins can obtain "&lt;my registry&gt;.azurecr.io/docker-ssh-slave-example"

The screenshots in https://github.com/jenkinsci/azure-container-agents-plugin/issues/29 indicate there is a "Kind" of credential called "Azure Container Registry".  When I attempt to create the "Registry credentials", there is no option by this name (screenshot below).

Please help me understand what needs to be setup to accomplish this.  How does the Jenkins  job authenticate with the Azure Container Registry?  Does it employ a method described in [Authenticate with a private Docker container registry](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-authentication) or does it rely on a different technique?

![image](https://user-images.githubusercontent.com/1558486/58111643-b69c6080-7ba6-11e9-9ac1-cd7f71bb3817.png)

**Comment by jleonelion** [comment]
I think there may be a bug.  I am using version 0.4.1 of the plugin.  When configuring "Private Registry Credentials" there are no options in the "Registry credentials" drop down (even though I have a list of global credentials defined for this Jenkins instance).  Whenever I attempt to create a new credential (using the "Add" drop down next to the "Registry credentials" field on the Jenkins "Configure System" page) the credential gets created, but the drop down of "Registry credentials" does not show that credential as an option.  In other words, it is impossible to define "Registry credentials" for a private registry.

**Comment by gavinfish** [comment]
I think "Username with password" credential type for private registry is enough, "Azure Container Registry" in the case should be description or id something.

**Comment by jleonelion** [comment]
@gavinfish Thank you for the reply.  Unfortunately, at this point I am unable to associate any kind of credentials to a private registry via the UI (whether is be "username with password" or any of the "Kind" values listed in the drop down included in my prior screenshot).  Do you recommend I attempt to define the private registry (and the credentials Jenkins should use when interacting with that registry) using a groovy script?

**Comment by gavinfish** [comment]
I will release a new version for this plugin today, it can display credentials in the drop down list.

**Comment by jleonelion** [comment]
@gavinfish I downloaded the 1.0.0 version of the plugin and things are working as expected!
