### ISSUE TITLE
How to report an issue with azure vm agents plugin?

### ISSUE THREAD

**Issue by rychuhardy** [jenkinsci/azure-container-agents-plugin#45]
Sorry for creating issue here, but for the repository of azure vm agents there is no way create issue and no word about where to do it. The mentioned repo: https://github.com/jenkinsci/azure-vm-agents-plugin

**Comment by gavinfish** [comment]
@rychuhardy you can file an issue at https://issues.jenkins-ci.org/secure/Dashboard.jspa as most Jenkins issues are tracked there. Similar instruction at https://github.com/jenkinsci/windows-azure-storage-plugin#reporting-bugs-and-feature-requests.
