### ISSUE TITLE
Container Instances - Use of Private IPS

### ISSUE THREAD

**Issue by alfador1** [jenkinsci/azure-container-agents-plugin#55]
Hello,
At the moment Jenkins plugin forces us to use public address. 
Allowing jnlp ports through public address works.
However we need to connect Jenkins Master by Private IP. We don't want to expose any public address ports to the Jenkins

However it seems that ACI uses it's own network and cannot directly access our Jenkins.
What can we do. it is a pretty critical component not working

**Comment by jplorier** [comment]
We are on the same situation. ACI has the possibility to spawn containers specifying whether it will use public, private or none network ip. With private, it should use the RG lan but we have no option in the plugin

**Comment by jplorier** [comment]
I've tried to contact the repository owners to allow me to push a new branch with the code for a new parameter. I've created a new issue #59 for this.

**Comment by sparsick** [comment]
Using private address for container forces to set up a network profile. That means also, the Jenkins master and the container must be in the same virtual network.
