### ISSUE TITLE
Add NoDelayProvisionerStrategy to reduce provisioning time of AKS pods

### ISSUE THREAD

**Issue by dileep626** [jenkinsci/azure-container-agents-plugin#61]
Currently, Jenkins waits for existing pods to complete execution, and only after some time it provisions a new pod on Azure Kubernetes (AKS).
This was [fixed](https://issues.jenkins-ci.org/browse/JENKINS-56307) for the [Kubernetes](https://plugins.jenkins.io/kubernetes/) plugin

Need to add this to Azure container agents plugin for reducing provisioning time.
Also, it'll be helpful if we can provide a flag to choose from
- wait for existing pods/executors
- create new pod for every build

**Comment by timja** [comment]
Kubernetes support was removed from this plugin
