### ISSUE TITLE
Enhancements to azure plugins

### ISSUE THREAD

**Issue by timja** [jenkinsci/azure-container-agents-plugin#69]
Hi 👋 

Just creating an umbrella issue to cover some maintenance changes I would like to make to the Azure plugins we're co-maintaining.

* Switch default branch to master
* Ensure all documentation is pulled from GitHub and not the wiki
* Switch release notes to GitHub releases
* Enable continuous delivery of plugins
* Enable GitHub issues for issue tracking
* Migrate issues from Jira to GitHub and delete the Jira component
* Stretch goal: Create pipeline(s) for running integration tests with comment ops

## Switch default branch to master

I don't see a reason to have a 'dev' branch here, all releasing is done on 'dev' and master is synced sometimes. One reason to change is that the plugin site has 'master' currently hardcoded for docs when you pass just the repository URL as the docs location, I noticed in azure-vm-agents that the docs were out of date and tracked it down to the master branch not being synced

## Ensure all documentation is pulled from GitHub and not the wiki

The Jenkins [wiki](https://wiki.jenkins.io/) cannot be updated any more, most of the plugins have been switched already (by updating the url field in pom.xml and doing a release after migrating the docs).

You can check which ones haven't been migrated on the [progress page](https://jenkins-wiki-exporter.jenkins.io/progress).

## Switch release notes to GitHub releases

Most plugins these days publish their release notes via release drafter which uses the PR title + a label to categorise, this means that users can subscribe to releases and know what's in side along with other tools that integrate with GitHub releases like the plugin site.

More info here: https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc
Example: https://github.com/jenkinsci/configuration-as-code-plugin/releases/tag/configuration-as-code-1.47

## Enable continuous delivery of plugins

[JEP-229](https://www.jenkins.io/jep/229) has provided a way for plugins to be automatically released on a merge to the main branch, this means that you don't have to worry about being around for a release and do it on your machine anymore, along with no more users asking on GitHub pull requests for a release after a change has been merged.

[Guide](https://github.com/jenkinsci/incrementals-tools#automatic-deployment) to implementing it.
[Example repo](https://github.com/jenkinsci/tekton-client-plugin/releases)

## Enable GitHub issues for issue tracking

GitHub issues tend to be a lot easier to manage as they are right with the code, they are far tighter integrated and don't require the extra maintenance work of Jira. Subscribing to issues is just a click in the repository rather than messing around with JQL filters in Jira. Users can go the repository and just click new issue, rather than trying to sign up for a Jenkins project account and figuring out the workflow. There's also a number of GitHub issue templates created by default to help projects.

## Migrate issues from Jira to GitHub and delete the Jira component

So that issues don't get lost / double reported etc we should migrate all the existing issues from Jira to GitHub

A project that has been mentioned before is: https://github.com/warden/jira-issues-importer

It could be run as a dry-run on a fork first

## Stretch goal: Create pipeline(s) for running integration tests with comment ops

Ideally I would like to have integration tests that aren't triggered automatically to save costs and protect against rogue PRs, but do allow triggering via a pull request. I'll probably spin this off into it's own issue

Let me know what you think @xuzhang3, and if you have any objections

Checklist:

- [x] https://github.com/jenkinsci/azure-container-agents-plugin
- [ ] https://github.com/jenkinsci/azure-vm-agents-plugin
- [ ] https://github.com/jenkinsci/azure-ad-plugin
- [ ] https://github.com/jenkinsci/azure-commons-plugin/
- [ ] https://github.com/jenkinsci/windows-azure-storage-plugin
- [ ] https://github.com/jenkinsci/azure-artifact-manager-plugin
- [ ] https://github.com/jenkinsci/azure-credentials-plugin
- [ ] https://github.com/jenkinsci/azure-keyvault-plugin (this one isn't co-maintained but I'll do it as well)

Template:

- [ ] Switch default branch to master
- [ ] Ensure all documentation is pulled from GitHub and not the wiki
- [ ] Switch release notes to GitHub releases
- [ ] Enable continuous delivery of plugins
- [ ] Enable GitHub issues for issue tracking
- [ ] Migrate issues from Jira to GitHub and delete the Jira component

**Comment by xuzhang3** [comment]
Hi @timja  Agree with your most of the suggestions.  Only one questions `Enable continuous delivery of plugins`:
I'm not familiarly with JEP-229 , will a new version be released every time a PR merged into the master? Sometimes,  a PR only update document.

**Comment by timja** [comment]
It will only release on 'interesting' changes:

https://github.com/jenkinsci/tekton-client-plugin/blob/master/.github/workflows/cd.yaml#L48-L69

And you will always have the option to manually click the trigger workflow button in the UI if you want to release a 'non-interesting' change, a normal example of that would be a dependency bump that is needed elsewhere.

**Comment by timja** [comment]
Azure container agents:

- [x] Switch default branch to master
- [x] Ensure all documentation is pulled from GitHub and not the wiki
- [x] Switch release notes to GitHub releases
- [x] Enable continuous delivery of plugins
- [x] Enable GitHub issues for issue tracking
- [ ] Migrate issues from Jira to GitHub and delete the Jira component

**Comment by timja** [comment]
Azure vm agents:

- [ ] Switch default branch to master
- [ ] Ensure all documentation is pulled from GitHub and not the wiki
- [ ] Switch release notes to GitHub releases
- [ ] Enable continuous delivery of plugins
- [ ] Enable GitHub issues for issue tracking
- [ ] Migrate issues from Jira to GitHub and delete the Jira component

**Comment by timja** [comment]
Azure AD:

- [ ] Switch default branch to master
- [ ] Ensure all documentation is pulled from GitHub and not the wiki
- [ ] Switch release notes to GitHub releases
- [ ] Enable continuous delivery of plugins
- [ ] Enable GitHub issues for issue tracking
- [ ] Migrate issues from Jira to GitHub and delete the Jira component

**Comment by timja** [comment]
Azure commons:

- [ ] Switch default branch to master
- [ ] Ensure all documentation is pulled from GitHub and not the wiki
- [ ] Switch release notes to GitHub releases
- [ ] Enable continuous delivery of plugins
- [ ] Enable GitHub issues for issue tracking
- [ ] Migrate issues from Jira to GitHub and delete the Jira component

**Comment by timja** [comment]
azure storage

- [ ] Switch default branch to master
- [ ] Ensure all documentation is pulled from GitHub and not the wiki
- [ ] Switch release notes to GitHub releases
- [ ] Enable continuous delivery of plugins
- [ ] Enable GitHub issues for issue tracking
- [ ] Migrate issues from Jira to GitHub and delete the Jira component

**Comment by timja** [comment]
artifact manager

- [ ] Switch default branch to master
- [ ] Ensure all documentation is pulled from GitHub and not the wiki
- [ ] Switch release notes to GitHub releases
- [ ] Enable continuous delivery of plugins
- [ ] Enable GitHub issues for issue tracking
- [ ] Migrate issues from Jira to GitHub and delete the Jira component

**Comment by timja** [comment]
credentials

- [ ] Switch default branch to master
- [ ] Ensure all documentation is pulled from GitHub and not the wiki
- [ ] Switch release notes to GitHub releases
- [ ] Enable continuous delivery of plugins
- [ ] Enable GitHub issues for issue tracking
- [ ] Migrate issues from Jira to GitHub and delete the Jira component

**Comment by timja** [comment]
key vault

- [ ] Switch default branch to master
- [ ] Ensure all documentation is pulled from GitHub and not the wiki
- [ ] Switch release notes to GitHub releases
- [ ] Enable continuous delivery of plugins
- [ ] Enable GitHub issues for issue tracking
- [ ] Migrate issues from Jira to GitHub and delete the Jira component

**Comment by timja** [comment]
All done
