### ISSUE TITLE
"Resource Group" need to be empty in Azure

### ISSUE THREAD

**Issue by raphaelquati** [jenkinsci/azure-container-agents-plugin#8]
Changes in ACI requires an empty resource group.
So the plugin don't launch a new instance in existing resource group.

**Comment by zackliu** [comment]
Seems Azure didn't mention ACI requires empty resource group and actually I can provision more than one agent concurrently in an existing resource group with a storage account inside in advance.
Could you give me the context of provision failed.

**Comment by raphaelquati** [comment]
I've created a test environment before days ago.
Starting a test build again, the container is not started.
Pipeline shows:

![image](https://user-images.githubusercontent.com/815086/32562758-9cdaa4a4-c496-11e7-8f33-e044cc43886d.png)

So in Azure Portal, I've tried to create an new instance manualy with the same resource group specified before:

![image](https://user-images.githubusercontent.com/815086/32563080-66be8344-c497-11e7-8157-a83e1393fd29.png)

So I've created a new resource group (empty), and changed in Jenkins. 
After that, the plugin start launching instances again.

**Comment by zackliu** [comment]
I did some test. Seems the limitation is set by Azure Portal.
I cannot create ACI in a nonempty resource group in portal but I can create it in plugin (plugin uses ARM Template directly).
So if your container can't start, can you do another test and give me the log (Manage Jenkins -> System log -> All Jenkins Logs) . If it really caused by the nonempty resource group, the deployment must be failed, and you can go to portal to get detail info why deployment failed.

If the deployment failed, you will get the logs like below:
> AciCloud: Provision agent aci-w4rwp failed: Deployment aci-bk171tl5 status: Failed
> Nov 09, 2017 1:45:53 AM INFO com.microsoft.jenkins.containeragents.aci.AciService deleteAciContainerGroup
> Delete ACI Container Group: aci-w4rwp successfully
> Nov 09, 2017 1:45:56 AM WARNING hudson.slaves.NodeProvisioner$2 run
> Unexpected exception encountered while provisioning agent aci
> java.lang.Exception: Deployment aci-bk171tl5 status: Failed
> 	at com.microsoft.jenkins.containeragents.aci.AciService.createDeployment(AciService.java:121)
> 	at com.microsoft.jenkins.containeragents.aci.AciContainerTemplate.provisionAgents(AciContainerTemplate.java:93)
> 	at com.microsoft.jenkins.containeragents.aci.AciCloud$1.call(AciCloud.java:103)
> Caused: java.lang.Exception
> 	at com.microsoft.jenkins.containeragents.aci.AciCloud$1.call(AciCloud.java:128)
> 	at com.microsoft.jenkins.containeragents.aci.AciCloud$1.call(AciCloud.java:79)
> 	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)

**Comment by raphaelquati** [comment]
I'm tested again now.
Jenkins version: 2.89
Azure Container Agents Plugin: 0.2.0
Pipeline:

```
parallel 'test1':{
    node('Linux') {
        withAWS(credentials: 'xxxxxxxx') {
            s3Download bucket: 'test1', file: 'teste.txt', path: 'd2/d5/'
    	}
    }
}, 'test2':{
    node('MACOS') {
        withAWS(credentials: 'xxxxxxxxxx') {
            s3Download bucket: 'test1', file: 'teste.txt', path: 'd2/d5/'
    	}
    }
}

```




Trying again, using an empty resource group.
Logs:
Nov 09, 2017 11:45:47 AM com.microsoft.jenkins.containeragents.aci.AciCleanTask cleanLeakedContainer
INFO: Starting to clean leaked containers for cloud Azure_ACI
Nov 09, 2017 11:45:47 AM okhttp3.internal.platform.Platform log
INFO: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
Nov 09, 2017 11:45:47 AM hudson.model.AsyncPeriodicWork$1 run
INFO: Finished ACI Period Clean Task. 558 ms
Nov 09, 2017 11:53:20 AM hudson.TcpSlaveAgentListener$ConnectionHandler run
INFO: Accepted JNLP4-connect connection #9 from /201.76.161.150:65137
Nov 09, 2017 11:54:08 AM hudson.TcpSlaveAgentListener$ConnectionHandler error
WARNING: Connection #10 is aborted: Unknown protocol:Protocol:CLI-connect
Nov 09, 2017 11:57:35 AM org.eclipse.jetty.server.session.Session beginInvalidate
INFO: Session node046z839cvyw3012lrrb6fn6oyt14 already being invalidated
Nov 09, 2017 11:57:58 AM com.microsoft.jenkins.containeragents.aci.AciCloud provision
INFO: Start ACI container for label Linux workLoad 1
Nov 09, 2017 11:57:58 AM com.microsoft.jenkins.containeragents.aci.AciCloud provision
INFO: Using ACI Container template: Linux Default
Nov 09, 2017 11:57:58 AM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning Linux Default from Azure_ACI with 1 executors. Remaining excess workload: 0
Nov 09, 2017 11:57:58 AM com.microsoft.jenkins.containeragents.aci.AciCloud$1 call
INFO: Add ACI node: linux-default-jtft9
Nov 09, 2017 11:58:00 AM okhttp3.internal.platform.Platform log
INFO: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
Nov 09, 2017 11:58:02 AM com.microsoft.jenkins.containeragents.aci.AciService createDeployment
INFO: Waiting for deployment linux-default-wvfzbcb4
Nov 09, 2017 11:58:14 AM hudson.slaves.CloudRetentionStrategy check
INFO: Disconnecting linux-default-jtft9
Nov 09, 2017 11:58:15 AM com.microsoft.jenkins.containeragents.aci.AciService deleteAciContainerGroup
INFO: Delete ACI Container Group: linux-default-jtft9 successfully
Nov 09, 2017 11:58:32 AM com.microsoft.jenkins.containeragents.aci.AciCloud$1 call
WARNING: AciCloud: Provision agent linux-default-jtft9 failed: Deployment linux-default-wvfzbcb4 status: Failed
Nov 09, 2017 11:58:38 AM hudson.slaves.NodeProvisioner$2 run
WARNING: Unexpected exception encountered while provisioning agent Linux Default
java.lang.Exception: java.lang.Exception: Deployment linux-default-wvfzbcb4 status: Failed
	at com.microsoft.jenkins.containeragents.aci.AciCloud$1.call(AciCloud.java:128)
	at com.microsoft.jenkins.containeragents.aci.AciCloud$1.call(AciCloud.java:79)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.Exception: Deployment linux-default-wvfzbcb4 status: Failed
	at com.microsoft.jenkins.containeragents.aci.AciService.createDeployment(AciService.java:121)
	at com.microsoft.jenkins.containeragents.aci.AciContainerTemplate.provisionAgents(AciContainerTemplate.java:93)
	at com.microsoft.jenkins.containeragents.aci.AciCloud$1.call(AciCloud.java:103)
	... 6 more

Nov 09, 2017 11:58:38 AM com.microsoft.jenkins.containeragents.aci.AciCloud provision
INFO: Start ACI container for label Linux workLoad 1
Nov 09, 2017 11:58:38 AM com.microsoft.jenkins.containeragents.aci.AciCloud provision
INFO: Using ACI Container template: Linux Default
Nov 09, 2017 11:58:38 AM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning Linux Default from Azure_ACI with 1 executors. Remaining excess workload: 0
Nov 09, 2017 11:58:38 AM com.microsoft.jenkins.containeragents.aci.AciCloud$1 call
INFO: Add ACI node: linux-default-1zgln
Nov 09, 2017 11:58:38 AM com.microsoft.jenkins.containeragents.aci.AciService createDeployment
INFO: Waiting for deployment linux-default-20cj22xq
Nov 09, 2017 11:59:14 AM hudson.slaves.CloudRetentionStrategy check
INFO: Disconnecting linux-default-1zgln
Nov 09, 2017 11:59:14 AM com.microsoft.jenkins.containeragents.aci.AciService deleteAciContainerGroup
INFO: Delete ACI Container Group: linux-default-1zgln successfully
Nov 09, 2017 11:59:19 AM com.microsoft.jenkins.containeragents.aci.AciCloud$1 call
WARNING: AciCloud: Provision agent linux-default-1zgln failed: Deployment linux-default-20cj22xq status: Failed
Nov 09, 2017 11:59:28 AM hudson.slaves.NodeProvisioner$2 run
WARNING: Unexpected exception encountered while provisioning agent Linux Default
java.lang.Exception: java.lang.Exception: Deployment linux-default-20cj22xq status: Failed
	at com.microsoft.jenkins.containeragents.aci.AciCloud$1.call(AciCloud.java:128)
	at com.microsoft.jenkins.containeragents.aci.AciCloud$1.call(AciCloud.java:79)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.Exception: Deployment linux-default-20cj22xq status: Failed
	at com.microsoft.jenkins.containeragents.aci.AciService.createDeployment(AciService.java:121)
	at com.microsoft.jenkins.containeragents.aci.AciContainerTemplate.provisionAgents(AciContainerTemplate.java:93)
	at com.microsoft.jenkins.containeragents.aci.AciCloud$1.call(AciCloud.java:103)
	... 6 more

Nov 09, 2017 11:59:28 AM com.microsoft.jenkins.containeragents.aci.AciCloud canProvision
WARNING: Cannot provision: template for label Linux is not available now, because it failed to provision last time. 
Nov 09, 2017 11:59:38 AM com.microsoft.jenkins.containeragents.aci.AciCloud provision
INFO: Start ACI container for label Linux workLoad 1
Nov 09, 2017 11:59:38 AM com.microsoft.jenkins.containeragents.aci.AciCloud provision
INFO: Using ACI Container template: Linux Default
Nov 09, 2017 11:59:38 AM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning Linux Default from Azure_ACI with 1 executors. Remaining excess workload: 0
Nov 09, 2017 11:59:38 AM com.microsoft.jenkins.containeragents.aci.AciCloud$1 call
INFO: Add ACI node: linux-default-x8j01
Nov 09, 2017 11:59:38 AM com.microsoft.jenkins.containeragents.aci.AciService createDeployment
INFO: Waiting for deployment linux-default-68r7bw52
Nov 09, 2017 12:00:14 PM hudson.slaves.CloudRetentionStrategy check
.....

The pipeline remains "in loop" trying to allocate a node.

In Azure Portal:

![image](https://user-images.githubusercontent.com/815086/32618715-a1f7e0a4-c55f-11e7-8f35-98b60ed85cf4.png)

![image](https://user-images.githubusercontent.com/815086/32618790-cef20080-c55f-11e7-93d2-2252613b286c.png)

**Comment by raphaelquati** [comment]
1 - Wait Jenkins to deallocate the node.
2 - Start again: loop error......

![image](https://user-images.githubusercontent.com/815086/32623168-5a8a9fb0-c56c-11e7-94eb-169877c23218.png)

![image](https://user-images.githubusercontent.com/815086/32623206-8246b4d0-c56c-11e7-9bc4-1b246bf5731f.png)

**Comment by raphaelquati** [comment]
![image](https://user-images.githubusercontent.com/815086/32623389-215cda68-c56d-11e7-8244-a78309a1ee4b.png)

![image](https://user-images.githubusercontent.com/815086/32624686-1ec09ef8-c571-11e7-9a2c-8d1d5087830d.png)

**Comment by zackliu** [comment]
OK, I think I get the point. The ACI deleted by retention strategy before deployment finished so deployment shows `ContainerGroupNotFound`. Which Retention Strategy did you choose? `Once` or `Idle`? I think it's `Idle` and set a small idle time.
So the workaround is choose `Once Retention Strategy` (recommend) or set a much larger idle time (larger than your provision time). I will fix this bug in the next release.

> Nov 09, 2017 11:58:14 AM hudson.slaves.CloudRetentionStrategy check
> INFO: Disconnecting linux-default-jtft9
> ...
> Nov 09, 2017 11:59:14 AM hudson.slaves.CloudRetentionStrategy check
> INFO: Disconnecting linux-default-1zgln

**Comment by raphaelquati** [comment]
You're right. I'm using Idle strategy with 5 min only.

![image](https://user-images.githubusercontent.com/815086/32641014-b890f79e-c5b2-11e7-9ac4-77868a2c14a3.png)

**Comment by zackliu** [comment]
#11
